# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./src/cmmlCalcTest.h

#Source files
SOURCES += ./main.cpp \
    ./src/cmmlCalcTest.cpp
