#include "../src/hmath/hmathbs/src/cdsrnumbers/number.h"
#include "../src/hmath/hmathbs/src/numbers/bitsett.h"
#include "../src/hmath/hmathbs/src/numbers/natural.h"
#include "../src/hmath/hmathbs/src/numbers/integer.h"
#include "../src/hmath/hmathbs/src/numbers/rational.h"
#include "../src/hmath/hmathbs/src/numbers/complex.h"
