# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


TEMPLATE = app
TARGET = testConsole
DESTDIR = /mmlsoft/run/win32/debug
CONFIG += debug console
INCLUDEPATH += /mmlsoft/include \
    ./GeneratedFiles/Debug \
    ./src
LIBS += -L"d:/mmlsoft/run/win32/debug" \
    -lhmathast \
    -lhmathbs \
    -lhutils
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/debug
OBJECTS_DIR += /mmlsoft/int/win32/debug/testConsole
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles

#Include file(s)
include(testConsole.pri)
