/****************************************************************************
**
** Copyright (C) 2010 Andriy Kovalchuk, Vyacheslav Levytskyy,
** Igor Samolyuk, Valentyn Yanchuk (aka "Hermitech Laboratory")
**
** All rights reserved.
** Contact: Hermitech Laboratory (info@mmlsoft.com)
**
** This file is a part of the Formulator MathML Editor project
** (http://www.mmlsoft.com).
**
** Commercial Usage
** Licensees holding valid Formulator Commercial licenses may use this 
** file in accordance with the Formulator Commercial License Agreement 
** provided with the Software or, alternatively, in accordance with the 
** terms contained in a written agreement between you and 
** Hermitech Laboratory.
**
** GNU General Public License Usage
** Alternatively, this file may be used under the terms of the GNU
** General Public License version 3.0 as published by the Free Software
** Foundation and appearing in the file LICENSE.GPL included in the
** packaging of this file.  Please review the following information to
** ensure the GNU General Public License version 3.0 requirements will be
** met: http://www.gnu.org/copyleft/gpl.html.
**
** If you have questions regarding the use of this file, please contact
** Hermitech Laboratory at info@mmlsoft.com.
**
****************************************************************************/

#include "mml_tag2mml.h"
#include "mml_operator.h"

HMathOpAttr HMathOpAttr_OperatorDictionary[ HMathOpAttr_OPERATOR_NUMBER ] =
{ 
	HMathOpAttr( _T("&hairsp;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("1-point space"),	-1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&thinsp;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("thin space"),	-1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&ThinSpace;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("thin space"),	-1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&VeryThinSpace;"),		HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("very thin space"),	-1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&ThickSpace;"),		HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("thick space"),	-1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&ZeroWidthSpace;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("zero width space"),	-1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&emsp13;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("thick space"),	-1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&emsp14;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("emsp14"),	-1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&emsp;"),		HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("em space"),	-1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&ensp;"),		HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("en space"),	-1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&MediumSpace;"),		HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("medium space"),	-1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&nbsp;"),		HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("nbsp space"),	-1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&NonBreakingSpace;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("nbsp space"),	-1, mmlPrecedence_Atom ),

	HMathOpAttr( _T("("),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text ("),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T(")"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text )"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("["),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text ["),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("]"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text ]"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("{"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text {"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("}"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text }"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&langle;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text <"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&lang;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text <"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&rangle;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text >"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&rang;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text >"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&quot;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("\""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("\""),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("\""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&OpenCurlyDoubleQuote;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&OpenCurlyQuote;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&CloseCurlyDoubleQuote;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&CloseCurlyQuote;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("|"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("text |"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&verbar;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text |"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Verbar;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text ||"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Verbar;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text ||"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Vert;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text ||"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Vert;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text ||"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&lfloor;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("@lfloor"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&rfloor;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("@rfloor"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&lceil;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("@lceil"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&rceil;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("@rceil"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&VerticalLine;"),	HMathOpAttr_FORM_INFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text |"),	HMathOpAttr_MINSIZE_NULL, mmlPrecedence_Atom ), //HMathOpAttr( _T("&VerticalLine;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("|"),	HMathOpAttr_MINSIZE_NULL, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&vert;"),	HMathOpAttr_FORM_INFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text |"),	HMathOpAttr_MINSIZE_NULL, mmlPrecedence_Atom ), //HMathOpAttr( _T("&vert;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("|"),	HMathOpAttr_MINSIZE_NULL, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&verbar;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text |"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("_"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("_"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&lowbar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("_"),	1, mmlPrecedence_Atom ),

	HMathOpAttr( _T("&LeftCeiling;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("@lceil"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&RightCeiling;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("@rceil"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&LeftFloor;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("@lfloor"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&RightFloor;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("@rfloor"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&LeftAngleBracket;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text <"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&LeftBracketingBar;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text |"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&LeftDoubleBracket;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("["),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&LeftDoubleBracketingBar;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text ||"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&RightAngleBracket;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text >"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&RightBracketingBar;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text |"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&RightDoubleBracket;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("]"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&RightDoubleBracketingBar;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	1,	0.0,	0.0,	_T("text ||"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&LeftSkeleton;"),	HMathOpAttr_FORM_PREFIX,	1,	0,	0,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&RightSkeleton;"),	HMathOpAttr_FORM_POSTFIX,	1,	0,	0,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&InvisibleComma;"),	HMathOpAttr_FORM_INFIX,	0,	1,	0,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T(","),	HMathOpAttr_FORM_INFIX,	0,	1,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_verythickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&HorizontalLine;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	0.0,	0.0,	_T(""),	HMathOpAttr_MINSIZE_NULL, mmlPrecedence_Atom ),
	HMathOpAttr( _T(";"),	HMathOpAttr_FORM_INFIX,	0,	1,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T(";"),	HMathOpAttr_FORM_POSTFIX,	0,	1,	0,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T(":="),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(":="),	1, mmlPrecedence_assign ),
	HMathOpAttr( _T("&Assign;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(":="),	1, mmlPrecedence_assign ),
	HMathOpAttr( MML_OPERATOR_BODY_ASSIGN,	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(":="),	1, mmlPrecedence_assign ),
	HMathOpAttr( _T("&Because;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&there4;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@therefore"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Therefore;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@therefore"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&VerticalSeparator;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("//"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Colon;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("*="),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_eq ),
	HMathOpAttr( _T("-="),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_eq ),
	HMathOpAttr( _T("+="),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_eq ),
	HMathOpAttr( _T("/="),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_eq ),
	HMathOpAttr( _T("->"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T(":"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T(".."),	HMathOpAttr_FORM_POSTFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_mediummathspace,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("..."),	HMathOpAttr_FORM_POSTFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_mediummathspace,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&SuchThat;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DoubleLeftTee;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DoubleRightTee;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DownTee;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&LeftTee;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&RightTee;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Implies;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_implies ),
	HMathOpAttr( _T("&RoundImplies;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_implies ),
	HMathOpAttr( _T("||"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T(""),	1, mmlPrecedence_and ),
	HMathOpAttr( _T("&or;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T("|"),	1, mmlPrecedence_and ),
	HMathOpAttr( _T("&Or;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T("|"),	1, mmlPrecedence_and ),
	HMathOpAttr( _T("&amp;&amp;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_and ),
	HMathOpAttr( _T("&"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&amp;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&and;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T("&"),	1, mmlPrecedence_and ),
	HMathOpAttr( _T("&And;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T("&"),	1, mmlPrecedence_and ),
	HMathOpAttr( _T("&amp;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&amp;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("!"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	0.0,	_T(""),	1, mmlPrecedence_unary ),
	HMathOpAttr( _T("!"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_unary ),
	HMathOpAttr( _T("&not;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_thickmathspace,	_T("!"),	1, mmlPrecedence_unary ),
	HMathOpAttr( _T("&Not;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_thickmathspace,	_T("!"),	1, mmlPrecedence_unary ),
	HMathOpAttr( _T("&exist;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_thickmathspace,	_T("@exist"),	1, mmlPrecedence_Last ),
	HMathOpAttr( _T("&Exists;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_thickmathspace,	_T("@exist"),	1, mmlPrecedence_Last ),
	HMathOpAttr( _T("&forall;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_thickmathspace,	_T("@forall"),	1, mmlPrecedence_Last ),
	HMathOpAttr( _T("&ForAll;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_thickmathspace,	_T("@forall"),	1, mmlPrecedence_Last ),
	HMathOpAttr( _T("&NotExists;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Last ),
	HMathOpAttr( _T("&Element;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@in"),	1, mmlPrecedence_in ),
	HMathOpAttr( _T("&NotElement;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@not_in"),	1, mmlPrecedence_in ),
	HMathOpAttr( _T("&NotReverseElement;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_in ),
	HMathOpAttr( _T("&NotSquareSubset;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_in ),
	HMathOpAttr( _T("&NotSquareSubsetEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_in ),
	HMathOpAttr( _T("&NotSquareSuperset;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_in ),
	HMathOpAttr( _T("&NotSquareSupersetEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_in ),
	HMathOpAttr( _T("&NotSubset;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@set_not_in"),	1, mmlPrecedence_in ),
	HMathOpAttr( _T("&NotSubsetEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@set_not_in_eq"),	1, mmlPrecedence_in ),
	HMathOpAttr( _T("&nsube;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@set_not_in_eq"),	1, mmlPrecedence_in ),
	HMathOpAttr( _T("&nsubE;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@set_not_in_eq"),	1, mmlPrecedence_in ),
	HMathOpAttr( _T("&nsubseteq;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@set_not_in_eq"),	1, mmlPrecedence_in ),
	HMathOpAttr( _T("&nsubseteqq;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@set_not_in_eq"),	1, mmlPrecedence_in ),
	HMathOpAttr( _T("&NotSuperset;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_in ),
	HMathOpAttr( _T("&NotSupersetEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_in ),
	HMathOpAttr( _T("&subnE;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@set_with_not_in_eq"),	1, mmlPrecedence_in ),
	HMathOpAttr( _T("&supnE;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@set_with_not_in_eq_inv"),	1, mmlPrecedence_in ),
	HMathOpAttr( _T("&bsim;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T("reversed ~"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&bcong;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("all_equal_to"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&ReverseElement;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_in ),
	HMathOpAttr( _T("&SquareSubset;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_in ),
	HMathOpAttr( _T("&SquareSubsetEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_in ),
	HMathOpAttr( _T("&SquareSuperset;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_in ),
	HMathOpAttr( _T("&SquareSupersetEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_in ),
	HMathOpAttr( _T("&Subset;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@set_in"),	1, mmlPrecedence_in ),
	HMathOpAttr( _T("&SubsetEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_in ),
	HMathOpAttr( _T("&vltri;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@normal_subgroup"),	1, mmlPrecedence_in ),
	HMathOpAttr( _T("&vrtri;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@cnormal_subgroup"),	1, mmlPrecedence_in ),
	HMathOpAttr( _T("&Superset;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@set_in_inv"),	1, mmlPrecedence_in ),
	HMathOpAttr( _T("&SupersetEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_in ),
	HMathOpAttr( _T("&DoubleLeftArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DoubleLeftRightArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DoubleRightArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DownLeftRightVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DownLeftTeeVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&lhard;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@harpoon_ld"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&leftharpoondown;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@harpoon_ld"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DownLeftVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@harpoon_ld"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DownLeftVectorBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DownRightTeeVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DownRightVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DownRightVectorBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&larr;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@arrow_l"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&leftarrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@arrow_l"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&LeftArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@arrow_l"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&ShortLeftArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@arrow_l"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&slarr;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@arrow_l"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&LeftArrowBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&LeftArrowRightArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&harr;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@arrow_h"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&leftrightarrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@arrow_h"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&LeftRightArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@arrow_h"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&LeftRightVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&LeftTeeArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&LeftTeeVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&LeftVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&LeftVectorBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&LowerLeftArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&LowerRightArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&rarr;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@arrow_r"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&rightarrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@arrow_r"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&RightArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@arrow_r"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&ShortRightArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@arrow_r"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&srarr;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@arrow_r"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&RightArrowBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&RightArrowLeftArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&RightTeeArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&RightTeeVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&rharu;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@harpoon_ru"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&rightharpoonup;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@harpoon_ru"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&RightVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@harpoon_ru"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&RightVectorBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&ShortLeftArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&ShortRightArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&UpperLeftArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&UpperRightArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("="),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@assign_eq"),	1, mmlPrecedence_eq ),
	HMathOpAttr( _T("&lt;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("<"),	1, mmlPrecedence_gt ),
	HMathOpAttr( _T("<"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("<"),	1, mmlPrecedence_gt ),
	HMathOpAttr( _T("&Lt;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("<<"),	1, mmlPrecedence_gt ),
	HMathOpAttr( _T("&gt;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(">"),	1, mmlPrecedence_gt ),
	HMathOpAttr( _T(">"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(">"),	1, mmlPrecedence_gt ),
	HMathOpAttr( _T("&Gt;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(">>"),	1, mmlPrecedence_gt ),
	HMathOpAttr( _T("!="),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("!="),	1, mmlPrecedence_eq ),
	HMathOpAttr( _T("&ne;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("!="),	1, mmlPrecedence_eq ),
	HMathOpAttr( _T("=="),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_eq ),
	HMathOpAttr( _T("&equiv;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@identical"),	1, mmlPrecedence_eq ),
	HMathOpAttr( _T("&lt;="),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(">="),	1, mmlPrecedence_geq ),
	HMathOpAttr( _T(">="),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(">="),	1, mmlPrecedence_geq ),
	HMathOpAttr( _T("&Congruent;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_eq ),
	HMathOpAttr( _T("&CupCap;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DotEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@approaches"),	1, mmlPrecedence_eq ),
	HMathOpAttr( _T("&esdot;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&wedgeq;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@estimates"),	1, mmlPrecedence_eq ),
	HMathOpAttr( _T("&trie;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@delta_equal"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&spar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("par text ||"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DoubleVerticalBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("par text ||"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&par;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("par text ||"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&parallel;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("par text ||"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&shortparallel;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("par text ||"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Equal;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_eq ),
	HMathOpAttr( _T("&EqualTilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_eq ),
	HMathOpAttr( _T("&Equilibrium;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_eq ),
	HMathOpAttr( _T("&GreaterEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_geq ),
	HMathOpAttr( _T("&GreaterEqualLess;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_geq ),
	HMathOpAttr( _T("&GreaterFullEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_geq ),
	HMathOpAttr( _T("&GreaterGreater;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt ),
	HMathOpAttr( _T("&GreaterLess;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt ),
	HMathOpAttr( _T("&GreaterSlantEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_geq ),
	HMathOpAttr( _T("&GreaterTilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt ),
	HMathOpAttr( _T("&HumpDownHump;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&HumpEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&LeftTriangle;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&LeftTriangleBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&LeftTriangleEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&le;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("<="),	1, mmlPrecedence_geq ),
	HMathOpAttr( _T("&ge;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(">="),	1, mmlPrecedence_geq ),
	HMathOpAttr( _T("&LessEqualGreater;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_geq ),
	HMathOpAttr( _T("&LessFullEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_geq ),
	HMathOpAttr( _T("&LessGreater;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_geq ),
	HMathOpAttr( _T("&LessLess;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt ),
	HMathOpAttr( _T("&LessSlantEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_geq ),
	HMathOpAttr( _T("&LessTilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt ),
	HMathOpAttr( _T("&NestedGreaterGreater;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt ),
	HMathOpAttr( _T("&NestedLessLess;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt ),
	HMathOpAttr( _T("&NotCongruent;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_eq ),
	HMathOpAttr( _T("&NotCupCap;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&NotDoubleVerticalBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&NotEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("!="),	1, mmlPrecedence_eq ),
	HMathOpAttr( _T("&NotEqualTilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_eq ),
	HMathOpAttr( _T("&NotGreater;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt ),
	HMathOpAttr( _T("&NotGreaterEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_geq ),
	HMathOpAttr( _T("&NotGreaterFullEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_geq ),
	HMathOpAttr( _T("&NotGreaterGreater;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt ),
	HMathOpAttr( _T("&NotGreaterLess;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt ),
	HMathOpAttr( _T("&NotGreaterSlantEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_geq ),
	HMathOpAttr( _T("&NotGreaterTilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt ),
	HMathOpAttr( _T("&NotHumpDownHump;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&NotHumpEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_eq ),
	HMathOpAttr( _T("&NotLeftTriangle;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&NotLeftTriangleBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&NotLeftTriangleEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_eq ),
	HMathOpAttr( _T("&NotLess;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt ),
	HMathOpAttr( _T("&NotLessEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_geq ),
	HMathOpAttr( _T("&NotLessFullEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_geq ),
	HMathOpAttr( _T("&NotLessGreater;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt ),
	HMathOpAttr( _T("&NotLessLess;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt ),
	HMathOpAttr( _T("&NotLessSlantEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_geq ),
	HMathOpAttr( _T("&NotLessTilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt ),
	HMathOpAttr( _T("&NotNestedGreaterGreater;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt ),
	HMathOpAttr( _T("&NotNestedLessLess;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_gt ),
	HMathOpAttr( _T("&NotPrecedes;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&NotPrecedesEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&NotPrecedesSlantEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&NotPrecedesTilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&NotRightTriangle;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&NotRightTriangleBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&NotRightTriangleEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&NotSucceeds;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&NotSucceedsEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&NotSucceedsSlantEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&NotSucceedsTilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&NotTilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&NotTildeEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&NotTildeFullEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&NotTildeTilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&NotVerticalBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Precedes;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@precedes"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&PrecedesEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&PrecedesSlantEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&PrecedesTilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Proportion;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&prop;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@proportional"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Proportional;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@proportional"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&ReverseEquilibrium;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&RightTriangle;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&RightTriangleBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&RightTriangleEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Succeeds;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@succeeds"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&SucceedsEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&SucceedsSlantEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&SucceedsTilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&sim;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("~"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Tilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("~"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&tilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T("~"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("~"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("~"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&TildeEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("~-"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&sime;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("~-"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&cong;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("~="),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&TildeFullEqual;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("~="),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&ap;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@almost_equal"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&TildeTilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T("@almost_equal"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&UpTee;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&VerticalBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thickmathspace,	HMathOpAttr_SPACE_thickmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&SquareUnion;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T(""),	1, mmlPrecedence_intersect ),
	HMathOpAttr( _T("&Union;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T("@sadd"),	1, mmlPrecedence_intersect ),
	HMathOpAttr( _T("&UnionPlus;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T(""),	1, mmlPrecedence_intersect ),
	HMathOpAttr( _T("&minus;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T("@minus"),	1, mmlPrecedence_add ),
	HMathOpAttr( _T("-"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T("@minus"),	1, mmlPrecedence_add ),
	HMathOpAttr( _T("+"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T("@plus"),	1, mmlPrecedence_add ),
	HMathOpAttr( _T("&plus;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T("@plus"),	1, mmlPrecedence_add ),
	HMathOpAttr( _T("&Intersection;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T("@smul"),	1, mmlPrecedence_intersect ),
	HMathOpAttr( _T("&MinusPlus;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T(""),	1, mmlPrecedence_add ),
	HMathOpAttr( _T("&PlusMinus;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T("@plusminus"),	1, mmlPrecedence_add ),
	HMathOpAttr( _T("&SquareIntersection;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T(""),	1, mmlPrecedence_intersect ),
	HMathOpAttr( _T("&Vee;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&CircleMinus;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T(""),	1, mmlPrecedence_add ),
	HMathOpAttr( _T("&CirclePlus;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@circle_plus"),	1, mmlPrecedence_add ),
	HMathOpAttr( _T("&oplus;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@circle_plus"),	1, mmlPrecedence_add ),
	HMathOpAttr( _T("&sum;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@sum"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Sum;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@sum"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&sum;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@sum_nl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Sum;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@sum_nl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&sum;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@sum_ul"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Sum;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@sum_ul"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&sum;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@sum_uol"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Sum;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@sum_uol"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&sum;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@sum_subl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Sum;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@sum_subl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&sum;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@sum_subsupl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Sum;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@sum_subsupl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Union;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@union_nl"),	1, mmlPrecedence_intersect ),
	HMathOpAttr( _T("&Union;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@union_ul"),	1, mmlPrecedence_intersect ),
	HMathOpAttr( _T("&Union;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@union_uol"),	1, mmlPrecedence_intersect ),
	HMathOpAttr( _T("&Union;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@union_subl"),	1, mmlPrecedence_intersect ),
	HMathOpAttr( _T("&Union;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@union_subsupl"),	1, mmlPrecedence_intersect ),
	HMathOpAttr( _T("&UnionPlus;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T(""),	1, mmlPrecedence_intersect ),
	HMathOpAttr( _T("lim"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	1,	0,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("max"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	1,	0,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("min"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	1,	0,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&CircleMinus;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	0,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@circle_minus"),	1, mmlPrecedence_add ),
	HMathOpAttr( _T("&CirclePlus;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	0,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@circle_plus"),	1, mmlPrecedence_add ),
	HMathOpAttr( _T("&int;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@integral"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&cwconint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@cwintegral"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&conint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@cintegral"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&awconint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@awintegral"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Conint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@aintegral"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Int;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@dintegral"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&tint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@tintegral"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Cconint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@vintegral"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&ClockwiseContourIntegral;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@cwintegral_nl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&ClockwiseContourIntegral;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@cwintegral_ul"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&ClockwiseContourIntegral;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@cwintegral_subl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&cwconint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@cwintegral_nl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&cwconint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@cwintegral_ul"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&cwconint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@cwintegral_subl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&conint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@cintegral_nl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&conint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@cintegral_ul"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&conint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@cintegral_subl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&awconint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@awintegral_nl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&awconint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@awintegral_ul"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&awconint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@awintegral_subl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Conint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@aintegral_nl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Conint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@aintegral_ul"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Conint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@aintegral_subl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Integral;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@integral"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&int;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@integral_nl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Integral;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@integral_nl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Integral;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@integral_ul"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&int;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@integral_ul"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Integral;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@integral_uol"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&int;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@integral_uol"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Integral;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@integral_subl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&int;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@integral_subl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Integral;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@integral_subsupl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&int;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@integral_subsupl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Int;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@dintegral_nl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Int;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@dintegral_ul"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Int;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@dintegral_subl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&tint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@tintegral_nl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&tint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@tintegral_ul"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&tint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@tintegral_subl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Cconint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@vintegral_nl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Cconint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@vintegral_ul"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Cconint;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	0,	1,	0.0,	0.0,	_T("@vintegral_subl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&isin;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@in"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&isinv;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@in"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&notin;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@not_in"),	1, mmlPrecedence_in ),
	HMathOpAttr( _T("&sub;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@set_in"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&sup;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@set_in_inv"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&subE;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@set_in_eq"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&supE;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@set_in_eq_inv"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&vnsub;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@set_not_in"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&emptyv;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@set_empty"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Cup;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@sadd"),	1, mmlPrecedence_intersect ),
	HMathOpAttr( _T("&Cap;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@smul"),	1, mmlPrecedence_intersect ),
	HMathOpAttr( _T("&cup;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@sadd"),	1, mmlPrecedence_intersect ),
	HMathOpAttr( _T("&cap;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@smul"),	1, mmlPrecedence_intersect ),
	HMathOpAttr( _T("&VerticalTilde;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Wedge;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&CircleTimes;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@circle_times"),	1, mmlPrecedence_mult ),
	HMathOpAttr( _T("&otimes;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@circle_times"),	1, mmlPrecedence_mult ),
	HMathOpAttr( _T("&coprod;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@coproduct"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Coproduct;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@coproduct"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Coproduct;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@coproduct_nl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&coprod;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@coproduct_nl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Coproduct;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@coproduct_ul"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&coprod;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@coproduct_ul"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Coproduct;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@coproduct_uol"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&coprod;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@coproduct_uol"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Coproduct;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@coproduct_subl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&coprod;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@coproduct_subl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Coproduct;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@coproduct_subsupl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&coprod;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@coproduct_subsupl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&prod;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@product"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Product;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@product"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Product;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@product_nl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&prod;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@product_nl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Product;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@product_ul"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&prod;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@product_ul"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Product;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@product_uol"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&prod;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@product_uol"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Product;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@product_subl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&prod;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@product_subl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Product;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@product_subsupl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&prod;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@product_subsupl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Coproduct;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@coproduct"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&coprod;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@coproduct"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Product;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@product"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&prod;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@product"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Intersection;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@intersection_nl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Intersection;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@intersection_ul"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Intersection;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@intersection_uol"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Intersection;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@intersection_subl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Intersection;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	1,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@intersection_subsupl"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Star;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T(""),	1, mmlPrecedence_mult ),
	HMathOpAttr( _T("&CenterDot;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@center_dot"),	1, mmlPrecedence_mult ),
	HMathOpAttr( _T("&sdot;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@center_dot"),	1, mmlPrecedence_mult ),
	HMathOpAttr( _T("*"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("*"),	1, mmlPrecedence_mult ),
	HMathOpAttr( _T("&lowast;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("*"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&times;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@times"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&InvisibleTimes;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_mult ),
	HMathOpAttr( _T("&bull;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@bullet"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&CircleDot;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	0,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T(""),	1, mmlPrecedence_mult ),
	HMathOpAttr( _T("&CircleTimes;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	1,	1,	0,	0.0,	HMathOpAttr_SPACE_thinmathspace,	_T("@circle_times"),	1, mmlPrecedence_mult ),
	HMathOpAttr( _T("&Vee;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Wedge;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Diamond;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Backslash;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&sol;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("text /"),	1, mmlPrecedence_mult ),
	HMathOpAttr( _T("/"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("text /"),	1, mmlPrecedence_mult ),
	HMathOpAttr( _T("&divide;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_thinmathspace,	HMathOpAttr_SPACE_thinmathspace,	_T("@divide"),	1, mmlPrecedence_mult ),
	HMathOpAttr( _T("-"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_veryverythinmathspace,	_T("@minus"),	1, mmlPrecedence_add ),
	HMathOpAttr( _T("+"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_veryverythinmathspace,	_T(""),	1, mmlPrecedence_add ),
	HMathOpAttr( _T("&MinusPlus;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_veryverythinmathspace,	_T(""),	1, mmlPrecedence_add ),
	HMathOpAttr( _T("&PlusMinus;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_veryverythinmathspace,	_T(""),	1, mmlPrecedence_add ),
	HMathOpAttr( _T("."),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Cross;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("**"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&CircleDot;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_mult ),
	HMathOpAttr( _T("&SmallCircle;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Square;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Del;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&PartialD;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_verythinmathspace,	_T("@partiald"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&CapitalDifferentialD;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_verythinmathspace,	_T("@capitaldifferentiald"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DifferentialD;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_verythinmathspace,	_T("@differentiald"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Sqrt;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	1,	0.0,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DoubleDownArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DoubleLongLeftArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DoubleLongLeftRightArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DoubleLongRightArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DoubleUpArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DoubleUpDownArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DownArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DownArrowBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DownArrowUpArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DownTeeArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&LeftDownTeeVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&LeftDownVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&LeftDownVectorBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&LeftUpDownVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&LeftUpTeeVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&LeftUpVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&LeftUpVectorBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&LongLeftArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&LongLeftRightArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&LongRightArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&ReverseUpEquilibrium;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&RightDownTeeVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&RightDownVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&RightDownVectorBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&RightUpDownVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&RightUpTeeVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&RightUpVector;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&RightUpVectorBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&ShortDownArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&ShortUpArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&UpArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&UpArrowBar;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&UpArrowDownArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&UpDownArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&UpEquilibrium;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&UpTeeArrow;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	1,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&circ;"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("^"),	HMathOpAttr_FORM_INFIX,	0,	0,	1,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&lt;>"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_geq ),
	HMathOpAttr( _T("\'"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("!!"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&commat;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("@"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("--"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("--"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("++"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("++"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&ApplyFunction;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("@apply_function"),	1, mmlPrecedence_apply ),
	HMathOpAttr( _T("&af;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("@apply_function"),	1, mmlPrecedence_apply ),
	HMathOpAttr( _T("&InvisibleTimes;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("@invisible_times"),	1, mmlPrecedence_mult ),
	HMathOpAttr( _T("&it;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("@invisible_times"),	1, mmlPrecedence_mult ),
	HMathOpAttr( _T("&InvisibleComma;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("@invisible_coma"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&ic;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("@invisible_coma"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("?"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("_"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_verythinmathspace,	HMathOpAttr_SPACE_verythinmathspace,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Breve;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Cedilla;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DiacriticalGrave;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DiacriticalDot;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DiacriticalDoubleAcute;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DiacriticalLeftArrow;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DiacriticalLeftRightArrow;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DiacriticalLeftRightVector;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DiacriticalLeftVector;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DiacriticalAcute;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DiacriticalRightArrow;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DiacriticalRightVector;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DiacriticalTilde;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DoubleDot;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&DownBreve;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Hacek;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&Hat;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&macr;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&OverBar;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&OverBrace;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T("@overbrace"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&tcub;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T("@overbrace"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&OverBracket;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&OverParenthesis;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&TripleDot;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	0,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&UnderBar;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T("text _"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&UnderBrace;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T("@underbrace"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&bcub;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T("@underbrace"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&UnderBracket;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&UnderParenthesis;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&marker;"),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T("@nop"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&ExponentialE;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("@exp"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&exponentiale;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("@exp"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&ee;"),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	0.0,	_T("@exp"),	1, mmlPrecedence_Atom ),
	HMathOpAttr( _T("&frown;"),	HMathOpAttr_FORM_POSTFIX,	0,	0,	1,	0,	0,	1,	0.0,	0.0,	_T(""),	1, mmlPrecedence_Atom ),
	HMathOpAttr( QChar(0x2212),	HMathOpAttr_FORM_INFIX,	0,	0,	0,	0,	0,	0,	HMathOpAttr_SPACE_mediummathspace,	HMathOpAttr_SPACE_mediummathspace,	_T("@minus"),	1, mmlPrecedence_add ),
	HMathOpAttr( QChar(0x2212),	HMathOpAttr_FORM_PREFIX,	0,	0,	0,	0,	0,	0,	0.0,	HMathOpAttr_SPACE_veryverythinmathspace,	_T("@minus"),	1, mmlPrecedence_add )
};
